name: outlive
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.11.5


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  flutter_screenutil:
  get:
  gradient_borders:
  flutter_facebook_auth:
  firebase_messaging:
  image_picker:
  intl:
  flutter_contacts:

  permission_handler:
  flutter_native_contact_picker:
  http:
  shared_preferences:



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:


flutter:
  uses-material-design: true


  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: sfprodisplay
      fonts:
        - asset: assets/fonts/sf_pro_display/regular.otf
          weight: 400
        - asset: assets/fonts/sf_pro_display/medium.otf
          weight: 500
        - asset: assets/fonts/sf_pro_display/bold.otf
          weight: 700

    - family: inter
      fonts:
        - asset: assets/fonts/inter.ttf
